on: 
  push:
    branches:
      - main
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
      
    - name: 🚀 Transfer files and Run Composer Install
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        source: "." # diretório atual
        target: "/www/apiitep/"
        script: |
          cd /www/apiitep/
          composer install --no-dev --optimize-autoloader
